### ISSUE TITLE
can not set up layer proposal

### ISSUE THREAD

**Issue by mogujiexuange** [HermannHesse/faster_rcnn_cplusplus#1]
I1130 20:03:11.124338 16824 net.cpp:411] rpn_cls_prob_reshape -> rpn_cls_prob_reshape
I1130 20:03:11.124387 16824 net.cpp:150] Setting up rpn_cls_prob_reshape
I1130 20:03:11.124403 16824 net.cpp:157] Top shape: 1 18 15 15 (4050)
I1130 20:03:11.124413 16824 net.cpp:165] Memory required for data: 21835056
I1130 20:03:11.124420 16824 layer_factory.hpp:77] Creating layer proposal
Segmentation fault

it happend when I run the demo....

**Comment by HermannHesse** [comment]
Hi @mogujiexuange,

are you able to run the [py-faster-rcnn demo](https://github.com/rbgirshick/py-faster-rcnn#demo) correctly?

On the other hand, did you compile caffe with `USE_CUDNN := 1`? I haven't tested it with this option yet.

Regards.

**Comment by Oli945** [comment]
@mogujiexuange,
have you solved this issue,I met the same problem

**Comment by maichm** [comment]
The same, does anyone solve this?

**Comment by HermannHesse** [comment]
Hello again @mogujiexuange @Oli945 @maichm, 

sorry for the delay but until today I did not get this error. It seems that (since the error doesn't indicate too much..) it is due to the different versions of the **Protocol Buffers** installed for C++ and Python. 

In my case, the installation with the default repositories of `protobuf-dev` installs version 2.6.1 (C++):

`apt-get install libprotobuf-dev`

and the installation of `protobuf` using `pip` for Python installs the latest one (3.5.1). For now we must use version 2.6.1 in both:

```
pip uninstall protobuf
pip install protobuf==2.6.1
```

I hope this solves the problem.

Best regards.
